DATABASE_URL: ${DATABASE_URL}
PORT: ${PORT}
JWT_SECRET: ${JWT_SECRET}
ACCESS_KEY: ${ACCESS_KEY}
SECRET_KEY: ${SECRET_KEY}
MINIO_BUCKET: ${MINIO_BUCKET}
MONGO_URI: ${MONGO_URI}
MONGO_DB_NAME: ${MONGO_DB_NAME}
REDIS_ADDR: ${REDIS_ADDR}
REDIS_PASS: ${REDIS_PASS}

KAFKA_BROKERS:
  - ${KAFKA_BROKERS}
KAFKA_TOPIC: ${KAFKA_TOPIC}

KEYCLOAK_REALM: ${KEYCLOAK_REALM}
KEYCLOAK_URL: ${KEYCLOAK_URL}
